version: '1.0'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./sites-available/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
